server.port=5000

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://Ravindra:Ravindra%402003@ac-9od3rn0-shard-00-00.zlvtb4u.mongodb.net:27017,ac-9od3rn0-shard-00-01.zlvtb4u.mongodb.net:27017,ac-9od3rn0-shard-00-02.zlvtb4u.mongodb.net:27017/smartpark?ssl=true&authSource=admin&retryWrites=true&w=majority

# JWT Configurations
jwt.secret=smartpark_jwt_secret_key_2024_secure

# Razorpay Configuration
razorpay.key.id=rzp_test_Sfpd6caKSNJFPG
razorpay.key.secret=8shlQ2uz8U1lColsNL5gyHg8

# Logging level
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb=INFO
